return {
{key="SUPER + ALT + UP",action="previous-tab"},
{key="SUPER + ALT + DOWN",action="next-tab"},
{key="SUPER + T",action="new-tab"},
{key="SUPER + W",action="close-tab"},
{key="SUPER + SHIFT + T",action="restore-tab"},
{key="SUPER + R",action="reload"},
{key="SUPER + SHIFT + R",action="reload-no-cache"},
{key="SUPER + N",action="new-window"},
{key="SUPER + SHIFT + N",action="private-window"},
{key="SUPER + SHIFT + W",action="close-window"},
{key="SUPER + SHIFT + D",action="pin-tab"},
{key="SUPER + M",action="mute-tab"},
{key="SUPER + H",action="history"},
{key="SUPER + ALT + H",action="history"},
{key="SUPER + SHIFT + C",action="copy-url"},
{key="SUPER + ALT + SHIFT + C",action="copy-url-markdown"},
{key="CTRL + D",action="duplicate-tab"},
{key="SUPER + code:34",action="back"},
{key="SUPER + code:35",action="forward"},
{key="SUPER + code:21",action="zoom-in"},
{key="SUPER + code:20",action="zoom-out"},
{key="SUPER + ALT + SHIFT + 0",action="zoom-reset"},
{key="SUPER + code:10",action="tab-1"},
{key="SUPER + code:11",action="tab-2"},
{key="SUPER + code:12",action="tab-3"},
{key="SUPER + code:13",action="tab-4"},
{key="SUPER + code:14",action="tab-5"},
{key="SUPER + code:15",action="tab-6"},
{key="SUPER + code:16",action="tab-7"},
{key="SUPER + code:17",action="tab-8"},
{key="SUPER + code:18",action="tab-9"},
{key="SUPER + L",shortcut="CTRL + L"},
{key="SUPER + F",shortcut="CTRL + F"},
{key="SUPER + J",shortcut="CTRL + G"},
{key="SUPER + K",shortcut="CTRL + SHIFT + G"},
{key="SUPER + D",shortcut="CTRL + D"},
{key="SUPER + P",shortcut="CTRL + P"},
{key="SUPER + S",shortcut="CTRL + S"},
{key="SUPER + SLASH",shortcut="CTRL + L"},
{key="SUPER + SHIFT + E",shortcut="CTRL + SHIFT + J"},
{key="SUPER + ALT + J",shortcut="CTRL + U"},
{key="SUPER + SHIFT + I",shortcut="CTRL + SHIFT + I"}
}
