set-option -g default-shell /usr/bin/zsh
set-environment -g PATH "/usr/local/bin:/usr/bin:/bin:$HOME/.local/bin:$PATH"
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.config/tmux/plugins/"

unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -as terminal-features ',xterm-ghostty:hyperlinks'

set -g mouse on
set -g base-index 1
set -g detach-on-destroy off
set -g escape-time 0
set -g history-limit 1000000
setw -g mode-keys vi
set -g renumber-windows on
set -g pane-border-status top
set-option -g status-position top

bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

unbind '"'
unbind %

bind [ copy-mode
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi C-v send -X rectangle-toggle
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel
bind-key -n M-v copy-mode

unbind x
bind x "kill-pane"

unbind &
bind & "kill-window"

bind k "kill-server"

bind-key ^ display-popup -E -w 90% -h 90% -T "lazygit" "lazygit"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'erikw/tmux-powerline'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'wfxr/tmux-fzf-url'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'off'

set -g status-style 'fg=color0,bg=color250'

set -g @sessionx-custom-paths "$HOME/Projects"
set -g @sessionx-custom-paths-subdirectories 'false'
set -g @sessionx-auto-accept 'off'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-filter-current 'false'

if-shell "test ! -d $HOME/.config/tmux/plugins/tpm" {
  run-shell "git clone https://github.com/tmux-plugins/tpm $HOME/.config/tmux/plugins/tpm && $HOME/.config/tmux/plugins/tpm/bin/install_plugins"
}

run-shell "$HOME/.config/tmux/plugins/tpm/tpm"

set -as terminal-features ",*:clipboard"
